# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20170607_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CG', 'CG'), ('P', 'P'), ('DC', 'DC'), ('AD', 'AD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='snippets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 10, 21, 55, 240362, tzinfo=utc)),
        ),
    ]
