# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_auto_20170607_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPatientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_status', models.CharField(max_length=9)),
                ('insurance_id', models.CharField(max_length=25)),
                ('organ_donor_status', models.BooleanField(default=False)),
                ('episode_type', models.CharField(max_length=14)),
                ('episode_number', models.IntegerField(max_length=4)),
                ('encounter_type', models.CharField(max_length=14)),
                ('encounter_no', models.IntegerField(max_length=4)),
                ('encounter_date_time', models.DateTimeField()),
                ('reason_for_visit', models.TextField(max_length=4096)),
                ('visit_date', models.DateField(default=datetime.datetime(2017, 6, 7, 19, 17, 28, 113189, tzinfo=utc))),
                ('care_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(max_length=11)),
                ('diagnosis_code_name', models.CharField(max_length=500)),
                ('diagnosis_code', models.CharField(max_length=500)),
                ('diagnosis_description', models.TextField(max_length=4096)),
                ('treatment_plan_investigations', models.TextField(max_length=4096)),
                ('treatment_plan_medication', models.TextField(max_length=4096)),
                ('treatment_plan_procedure', models.TextField(max_length=4096)),
                ('treatment_plan_referral', models.TextField(max_length=4096)),
                ('other_treatment_plan_type', models.TextField(max_length=10)),
                ('other_treatment_plan_details', models.TextField(max_length=4096)),
                ('current_clinical_status', models.TextField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 19, 17, 28, 115070, tzinfo=utc))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_history', models.TextField(max_length=4096)),
                ('past_history', models.TextField(max_length=4096)),
                ('family_history', models.TextField(max_length=4096)),
                ('menstural_obstetric_history', models.TextField(max_length=4096)),
                ('immunization_history', models.TextField(max_length=4096)),
                ('allergic_history', models.TextField(max_length=4096)),
                ('socio_eco_status', models.TextField(max_length=255)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitals_systolic_BP', models.IntegerField(max_length=3)),
                ('vitals_diastolic_BP', models.IntegerField(max_length=3)),
                ('pulse_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperature', models.IntegerField(max_length=3)),
                ('temperature_source', models.CharField(max_length=6)),
                ('respiration_rate', models.IntegerField(max_length=3)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_group', models.CharField(max_length=3)),
                ('clinical_exam_observation', models.TextField(max_length=4096)),
                ('investigation_result', models.TextField(max_length=4096)),
                ('date', models.DateField(default=datetime.datetime(2017, 6, 7, 19, 17, 28, 114200, tzinfo=utc))),
                ('care_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=500)),
                ('durg_code', models.CharField(max_length=500)),
                ('strength', models.CharField(max_length=500)),
                ('dose', models.CharField(max_length=500)),
                ('route', models.CharField(max_length=500)),
                ('frequency', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 19, 17, 28, 115889, tzinfo=utc))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='snippets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 19, 17, 28, 111149, tzinfo=utc)),
        ),
    ]
