# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 11:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_auto_20170608_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpatientstatus',
            name='visit_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 8, 11, 39, 53, 610433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='care_giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_giver_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 11, 39, 53, 614488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 11, 39, 53, 612716, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientmedicalstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 8, 11, 39, 53, 611492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 11, 39, 53, 613667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='snippets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 11, 39, 53, 608237, tzinfo=utc)),
        ),
    ]
