# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_auto_20170608_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpatientstatus',
            name='visit_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 8, 12, 13, 31, 125365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='completed_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 12, 13, 31, 129079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 12, 13, 31, 127391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientmedicalstatus',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 8, 12, 13, 31, 126463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 12, 13, 31, 128272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='snippets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 12, 13, 31, 123120, tzinfo=utc)),
        ),
    ]
